# Generated by Django 2.2.6 on 2019-10-26 19:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_auto_20191026_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='RFC',
            field=models.CharField(default='000-000-000', max_length=18),
        ),
        migrations.AddField(
            model_name='cliente',
            name='email',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='cliente',
            name='name',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='pedido',
            name='cliente',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to='pedidos.Cliente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='activo',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='cantidad',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='descripcion',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AddField(
            model_name='producto',
            name='name',
            field=models.CharField(default='', max_length=150),
        ),
    ]
