# Generated by Django 2.2.6 on 2019-10-26 19:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_auto_20191026_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='fecha_pedido',
            field=models.DateField(default=datetime.datetime(2019, 10, 26, 19, 49, 21, 890515)),
        ),
    ]
